In [1]:
# La descomposición de matrices en autovalores y autovectores soslo se efectua cuando es cuadrada.
# Pero para descomponer matrices no cuadradas, requerimos descomponerlo en valroes singualres.
#  Dadas 3 matruces u,v,d.
#  U.V son ortogonales.  
#  U tiene los vectores izquierdos singulares u1,u2,un...  
#  V tiene los vectores derecho singulares v1,v2,vn...
# NOTA: Son hasta n porque no tienen porque tener las mismas dirmensiones.
# D diagonal.

import numpy as np

In [2]:
# Haremso descompsoición singular en esta matriz.
A = np.array([[1,2,3], [3,4,5]])
print(A)

[[1 2 3]
 [3 4 5]]


In [3]:
# svd Nos permtie calcualar lso valores singualres.
U, D, V = np.linalg.svd(A)

In [4]:
# Matriz cuadrada
print(U)

[[-0.46410668 -0.88577931]
 [-0.88577931  0.46410668]]


In [5]:
print(D)

[7.97638869 0.61418515]


In [7]:
# Asi vemos la diagonal como tal.
print(np.diag(D))

[[7.97638869 0.        ]
 [0.         0.61418515]]


In [8]:

print(V)

[[-0.39133557 -0.5605708  -0.72980603]
 [ 0.8247362   0.13817999 -0.54837623]
 [ 0.40824829 -0.81649658  0.40824829]]


In [ ]:
#  A= U*D*V 
# Vectores y matrices peuden pensarse como subtranformaciones del espacio
# sI TUVIERAMOS MATRI 3X2 AL TRANSFORMAR EL ESPACIO ES cONVERTIR r3 A r2, ES DECIR, 
# ES CONDENSAR INFORMACIÓN QUE HABÍA EN UN TERCER EJE EN 
# DOS