In [5]:
import numpy as np

In [6]:
#Esto quiere decir que todos los resultados aproximados a cero con decimale smuy pequeños me lso arpxime a cero.
np.set_printoptions(suppress=True)

In [7]:
# Vamos a resolver 3x + y = 1  , 2x +y =1 

A = np.array([[3,1],[2,1]])
print(A)

[[3 1]
 [2 1]]


In [8]:
b = np.array([[1],[1]])

In [9]:
# Determino A^-1 con linalg.inv
inversa_A = np.linalg.inv(A)
print(inversa_A)

[[ 1. -1.]
 [-2.  3.]]


In [10]:
# Hago el producto interno de AI(b)
x = inversa_A.dot(b)
print(x)

[[0.]
 [1.]]


In [11]:
#La prubea de nuestra solución es AX = b
b1 =A.dot(x)
print(A.dot(x))
print(b1 == b )

[[1.]
 [1.]]
[[ True]
 [ True]]


In [12]:
#Igualamos nuestra ecuación a otros otros coeficientes. El nuevo b es 3 y 7 
sol_2 = inversa_A.dot(np.array([[3],[7]]))
print(sol_2)

[[-4.]
 [15.]]


In [13]:
#   Prueba de solución para AX= b
print(A.dot(sol_2))

[[3.]
 [7.]]


In [ ]:
##Los sistemas homogenoes son ventajosos ocmputaiconalemtne, pero debido a la forma en la que tratamos los números, debemos recurrir a aproximación numérica, que utilizan el valor de b para llegar a la solución correcta