In [10]:
import numpy as np
import matplotlib.pyplot as plt

#Tipos especiales de matrices: Identidad, Inversa, Singulares
# Identidad

identidad = np.eye(4)
#Me devuelve TODO flotante, los 1 y 0. ¿Porqué? Es el leemento neutro dentro de las matrices, es el 1 para los números.
#La identidad no transforma el espacio.


print(identidad)

#Transformación lienal, es tener un vector que transfomro cuando aplico o multiplico una matriz.

# Inversa
# A* X = AI
A = np.array([[-3, 1], [-2, 1]])
inversaA = np.linalg.inv(A)
print(f'Soy una matriz inversa \n {inversaA}')

#Identidad

I = np.array([[1,0,1],[0,1,1],[-1,1,1]])


#Matriz singular cuanod no existe la identidad.
print(f'Soy una matriz singular \n {A.dot(inversaA)}')


# Singular


[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Soy una matriz inversa 
 [[-1.  1.]
 [-2.  3.]]
Soy una matriz identidad 
 [[1.00000000e+00 0.00000000e+00]
 [2.22044605e-16 1.00000000e+00]]


In [ ]:
# Lo importante es entender que:
# Puedo calcular mis incognitas con la propiedad de 
# Ax= b
# x = b* A^-1



#