In [3]:
# La matriz diagonal y la matriz simétrica: sus propiedades
# Al multiplicar una matriz diagonal por un vector no necesariamente hay combinación, 
# es una ponderación de los elementos por lso que multiplica.
# Una matriz es simétrica cuando su transpuesta es igual a la matriz.
# Una matriz diagonal es simétrica porque tiene ceros arriba ya abajo
# (AB)^T = B^T A^T... Si A y B son simétricos entonces (AB)^T = BA, simplifica las cosas en el sentido de que se pueden calcular


import numpy as np

In [4]:
vector = np.array([1,2,3,4,5])

matriz = np.diag(vector)

print(matriz)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


In [5]:
print(matriz[0:4,0:3])

[[1 0 0]
 [0 2 0]
 [0 0 3]
 [0 0 0]]


In [6]:
print(matriz[0:3,0:4])

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]]


In [7]:
A = np.diag([2,3,4,5])
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [8]:
# Dado un vector v1 se busca hacer prodcto interno con la tranpeusta del vector 1.
v1 = np.array([[1,1,1,1]])

print(v1)

print(A.dot(v1.T))

[[1 1 1 1]]
[[2]
 [3]
 [4]
 [5]]


In [9]:
# A*A^-1 = I . El vector por su inversa me da la identidad.
# La diagonal del vector A.
A_inv = np.diag([1/2,1/3,1/4,1/5])
print(A_inv)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [11]:

# Computacionalmente si mi matriz inversa es simplemente dividir 1/elemento matriz entonces no son muhcas las operaciones
identidad = A.dot(A_inv)

print(identidad)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [12]:
# Se compara el método anterior mediante la comparacón de la función linalg.inv(a)
A_inv_calc = np.linalg.inv(A)
print(A_inv_calc)

[[0.5        0.         0.         0.        ]
 [0.         0.33333333 0.         0.        ]
 [0.         0.         0.25       0.        ]
 [0.         0.         0.         0.2       ]]


In [10]:
#Es simétrica y diagonal
print(A.T)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [11]:
#Es simétrica y diagonal
print(A)

[[2 0 0 0]
 [0 3 0 0]
 [0 0 4 0]
 [0 0 0 5]]


In [12]:
# Es como un espejoopuesto enla diagonal de cualquier matriz.
simetrica = np.array([[1,2,3],
                      [2,-1,7],
                      [3,7,11]])
print(simetrica)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]


In [13]:
print(simetrica.T)

[[ 1  2  3]
 [ 2 -1  7]
 [ 3  7 11]]
