In [23]:
#La inversa de Moore Penrose es una aplicación directa de svd nos
# permtie resolver en determinados momentos sistemas de ecuacione lineales
#  ax=B
# a^-1 =>X>B^-1 
# AA_pse aproximadamente es = I

# Descomposicón SVD
# Apse=V Dpse U.T

import numpy as np

np.set_printoptions(suppress=True)

In [24]:
A = np.array([[1,4], [2, 5], [-3, 6]])
print(A)

[[ 1  4]
 [ 2  5]
 [-3  6]]


In [25]:
U, D, V = np.linalg.svd(A)
print("U")
print(U)
print("D")
print(D)
print("V")
print(V)

U
[[-0.44700764  0.33725879  0.82851716]
 [-0.55337417  0.62345191 -0.55234477]
 [-0.70282373 -0.70538233 -0.09205746]]
D
[8.78936588 3.70770109]
V
[[ 0.06311209 -0.99800645]
 [ 0.99800645  0.06311209]]


In [26]:
#La pseudo inversa Moore Penrose, cuando verifica 4 condiciones existe y es única.
# Deinifmos uan matriz de ceros que tenga el mismo tamaño a la matriz orignal A.
# 
D_pse = np.zeros((A.shape[0], A.shape[1])).T
print(D_pse)

[[0. 0. 0.]
 [0. 0. 0.]]


In [27]:

print("Valores a reemplazar en D_pse")
print(D_pse[:D.shape[0], :D.shape[0]])

Valores a reemplazar en D_pse
[[0. 0.]
 [0. 0.]]


In [28]:
print("Valores que pondremos en D_pse")
print(np.linalg.inv(np.diag(D)))

Valores que pondremos en D_pse
[[0.11377385 0.        ]
 [0.         0.2697089 ]]


In [29]:
print("D_pse")
D_pse[:D.shape[0], :D.shape[0]] = np.linalg.inv(np.diag(D))
print(D_pse)

D_pse
[[0.11377385 0.         0.        ]
 [0.         0.2697089  0.        ]]


In [30]:
# lA MTARIZ QUE NOS MUESTRA PRODÍA O NO SE R UNA INVERSA DE A
A_pse = V.T.dot(D_pse).dot(U.T)
print(A_pse)

[[ 0.08757062  0.16384181 -0.19491525]
 [ 0.05649718  0.07344633  0.06779661]]


In [31]:
# Para validar que La matrizz A pseudoinversa calculamos la pseudo inversa de A.
A_pse_calc = np.linalg.pinv(A)
print(A_pse_calc)

[[ 0.08757062  0.16384181 -0.19491525]
 [ 0.05649718  0.07344633  0.06779661]]


In [32]:
# Esta matriz podria o no vritifca rlo que le pedimos. Queremos ver que acando aplciamos la pseudoniversa a la matriz a Es algo muy cercano a la identidad.
# el -0  es porque tenemos el suprres.Nos mostrará numeros muy pequeños.
print(A_pse.dot(A))

[[ 1. -0.]
 [-0.  1.]]


In [33]:
np.set_printoptions(suppress = False)

In [34]:
# Es un valro muy cercano a la inversa, e scercano, porque minimiza la norma 2 de estas instancias.
print(A_pse.dot(A))

[[ 1.00000000e+00 -2.22044605e-16]
 [-5.55111512e-17  1.00000000e+00]]


In [35]:
# Esot no tiene la propiedad que tiene una inversa comun. No puedo multiplicar a derecha o izqueirda.
# No son conmutativas. 
print(A.dot(A_pse))

[[ 0.31355932  0.45762712  0.07627119]
 [ 0.45762712  0.69491525 -0.05084746]
 [ 0.07627119 -0.05084746  0.99152542]]


In [36]:
# Segundo tipo de pseudo inversa. Me dará una matriz ue es ifual a la utilizada en el métod SVD, esta es más certera y tien emenos erroes
# computacionalmente hablando.

A_pse_2 = np.linalg.inv(A.T.dot(A)).dot(A.T)

print(A_pse_2)

[[ 0.08757062  0.16384181 -0.19491525]
 [ 0.05649718  0.07344633  0.06779661]]


In [37]:
print(A_pse)

[[ 0.08757062  0.16384181 -0.19491525]
 [ 0.05649718  0.07344633  0.06779661]]
